### ISSUE TITLE
弹出编辑/新增窗口之后怎么监听这个窗口被关闭/提交了呢

### ISSUE THREAD

**Issue by darknessp** [fallsea/fsLayui#15]
需要这个功能的目的是进行一些类似于统计的工作。比如我在页面上显示现在总共有多少行，新增一行之后我需要在页面上更新行数

**Comment by fallsea** [comment]
2.x 可以使用回调事件，https://www.wueasy.com/docs/fslayui/form/callback.html

**Comment by darknessp** [comment]
> 2.x 可以使用回调事件，https://www.wueasy.com/docs/fslayui/form/callback.html

谢谢
