### ISSUE TITLE
设置了fsLayedit，设值的疑问。

### ISSUE THREAD

**Issue by or0or1** [fallsea/fsLayui#4]
1，这样设置
 <textarea id="id_show_inf" name="show_inf" placeholder="" class="layui-textarea" height="240"></textarea>

使用document.getElementById("id_show_inf").value=output; 赋值生效。但高度不生效。

2，这样设置
 <textarea id="id_show_inf" name="show_inf" placeholder="" class="fsLayedit" height="240"></textarea>

使用document.getElementById("id_show_inf").value=output; 高度生效，但赋值失效。

使用方法2，该如何初始化富文本编辑框的内容？ 谢谢

**Comment by fallsea** [comment]
使用插件只要返回值有name，会自动赋值

**Comment by or0or1** [comment]
我改成： <textarea id="id_show_inf"  placeholder="" class="fsLayedit" height="240"></textarea>

结果也是一个的,赋值失效。 连textarea都没显示。

**Comment by fallsea** [comment]
layedit编辑器赋值请参考lay官网，http://www.layui.com/v1/doc/modules/layedit.html
