### ISSUE TITLE
弹出窗口中的select无法获取到传值

### ISSUE THREAD

**Issue by winstars** [fallsea/fsLayui#9]
我这里是一个新增窗口，并非编辑窗口，不从server端通过id回传整个form。
input=text时，form可以获取到弹出窗口的传值

> `<div class="layui-input-block" style="width: 300px;"><input type="text" name="deviceNo" required="" lay-verType="tips" lay-verify="required" placeholder="设备编码" autocomplete="off" class="layui-input" /></div>`

改成select后，获取不到传值。

> `<div class="layui-input-block" style="width: 300px;"><select name="deviceNo" lay-verify="required" lay-verType="tips" class="fsSelect fsDict" dict="devices" addNull="1" placeholder="请选择设备"></select></div>`

弹出窗口已经用inputs传值

> `inputs="deviceNo:"`

**Comment by fallsea** [comment]
升级1.8.4版本
